# Generated by Django 4.1.5 on 2023-02-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift_link', '0002_newworkout_newexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newexercise',
            name='workouts',
            field=models.ManyToManyField(related_name='exercises', to='lift_link.newworkout'),
        ),
    ]
