# Generated by Django 4.1.5 on 2023-02-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift_link', '0003_alter_newexercise_workouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newexercise',
            name='workouts',
        ),
        migrations.AddField(
            model_name='newworkout',
            name='exercises',
            field=models.ManyToManyField(related_name='workouts', to='lift_link.newexercise'),
        ),
    ]
