# Generated by Django 4.1.5 on 2023-02-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift_link', '0005_newexercise_weight_alter_newexercise_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newexercise',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
