# Generated by Django 4.1.5 on 2023-02-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift_link', '0006_alter_newexercise_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newexercise',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
