# Generated by Django 4.1.5 on 2023-02-04 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lift_link', '0007_alter_newexercise_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newexercise',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='newexercise',
            name='user',
        ),
    ]
