# Generated by Django 4.1.5 on 2023-02-09 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lift_link', '0008_remove_newexercise_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='title',
        ),
    ]
