# Generated by Django 4.1.5 on 2023-02-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift_link', '0009_remove_newpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
