# Generated by Django 4.1.5 on 2023-02-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift_link', '0012_newworkout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='newworkout',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
