# Generated by Django 4.1.5 on 2023-02-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift_link', '0013_newworkout_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newworkout',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
